const Pages = {
  homePage: '/',
  discover: '/discover',
  bookings: '/bookings',
  hostPeople: '/hostpeople',
  onBoarding: '/on-boarding',
  signin: '/signin',
  hostSignIn: '/host/signin',
  signup: '/signup',
  hostSignUp: '/host/signup',
  guestInfo: '/info',
  hostInfo: '/host/info',
  hostDetails: '/host/details',
  verification: '/verification',
  hostVerification: '/host/verification',
  hostCreated: '/host-created',
  guestCreated: '/guest-created',
  forgotPassword: '/forget-password',
  resetPassword: '/reset-password',
  resetCreated: '/reset-created',
  event: '/event',
  eventsLocation: '/events-location',
  guestDashboard: '/dashboard',
  hostDashboard: '/dashboard/host',
  hostDashboardSettings: '/dashboard/host/settings',
  hostDashboardEvents: '/dashboard/host/events',
  hostDashboardBookings: '/dashboard/host/bookings',
  hostDashboardWallet: '/dashboard/host/wallet',
  hostDashboardAnalytics: '/dashboard/host/analytics',
};

export default Pages;
